services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:8000'
        volumes:
            - './:/app'
        networks:
            - ollama
        restart: always
networks:
    ollama:
        external: true
