services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:8000'
        environment:
            - VIRTUAL_HOST=${APP_HOST}
        volumes:
            - './:/app'
        restart: always
